// src/Components/Newsroom/Panel/Card/index.tsx
import React from 'react';
import { INewsroomPanelCard } from './Card';

const NewsroomPanelCard: React.FunctionComponent<INewsroomPanelCard.IProps> = ({
  children,
  className,
}) => (
  <div className={className}>
    {children}
    <style jsx>
      {`
        div {
          border-radius: 0.25rem;
          box-shadow: 0 2.5px 7.5px rgba(0, 0, 0, 0.0375), 0 1.5px #e3e3e3;
          padding: 0.2rem 0.4rem;
          background-color: rgb(232, 232, 232);
          margin: 0.3rem 0;
          border: 1px solid transparent;
          transition: all 0.2s;
        }

        div:hover {
          border: 1px solid #555;
        }
      `}
    </style>
  </div>
);

export { NewsroomPanelCard };

// components/Card.vue
<template>
  <div class="card background-color">
    <slot></slot>
  </div>
</template>

<style scoped>
  .card {
    max-width: 35rem;
    width: 100%;
    display: block;
    padding: 1.5rem 2rem;
    margin-bottom: 1.25rem;
    border-radius: .5rem;
    z-index: 1000;
    box-shadow: none;
    transition: all .2s;
  }

  .card:hover {
    box-shadow: 0 20px 80px rgba(0,0,0,.1), 0 5px 20px rgba(0,0,0,.05);
  }

  @media (max-width: 600px) {
    .card {
      padding: 1.5rem 1rem;
    }
  }
</style>
