// components/Card.vue
<template>
  <div class="card background-color">
    <slot></slot>
  </div>
</template>

<style scoped>
  .card {
    max-width: 35rem;
    width: 100%;
    display: block;
    padding: 1.5rem 2rem;
    margin-bottom: 1.25rem;
    border-radius: .5rem;
    z-index: 1000;
    box-shadow: none;
    transition: all .2s;
  }

  .card:hover {
    box-shadow: 0 20px 80px rgba(0,0,0,.1), 0 5px 20px rgba(0,0,0,.05);
  }

  @media (max-width: 600px) {
    .card {
      padding: 1.5rem 1rem;
    }
  }
</style>

// src/Components/Basic/Card/index.tsx
import React from 'react';
import { ICard } from './Card';

export const Card: React.FunctionComponent<ICard.IProps> = ({ className, children }) => {
  return (
    <div className={`card background-color ${className || ''}`}>
      {children}
      <style jsx>
        {`
          .card {
            max-width: 35rem;
            width: 100%;
            display: block;
            padding: 1.5rem 2rem;
            margin-bottom: 1.25rem;
            border-radius: 0.5rem;
            z-index: 1000;
            box-shadow: none;
            transition: all 0.2s;
            background-color: #fff;
            -webkit-tap-highlight-color: rgba(0, 0, 0, 0);
          }

          .card:hover {
            box-shadow: 0 7.5px 32px rgba(0, 0, 0, 0.075), 0 2.5px 7.5px rgba(0, 0, 0, 0.0375);
          }

          @media (max-width: 600px) {
            .card {
              padding: 0.75rem 1rem;
              box-shadow: 0 5px 5px rgba(0, 0, 0, 0.025) !important;
            }
          }
        `}
      </style>
    </div>
  );
};
